language: java
sudo: false

services:
  - docker
  
jdk:
  - oraclejdk8

before_script:
# we need this line to allow code coverage reports
- export MAVEN_SKIP_RC=true

script: mvn clean verify -P run-its

after_success:
  - bash <(curl -s https://codecov.io/bash)